// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CmdProto {

  /// <summary>Holder for reflection information generated from cmd.proto</summary>
  public static partial class CmdReflection {

    #region Descriptor
    /// <summary>File descriptor for cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgljbWQucHJvdG8SCWNtZF9wcm90bxoKZ2FtZS5wcm90byIGCgRQaW5nIu8J",
            "Cg1Db21tb25NZXNzYWdlEhsKA2NtZBgBIAEoDjIOLmNtZF9wcm90by5DbWQS",
            "JwoJZXJyb3JDb2RlGAIgASgOMhQuY21kX3Byb3RvLkVycm9yQ29kZRIdCgRw",
            "aW5nGAMgASgLMg8uY21kX3Byb3RvLlBpbmcSLgoMY2xpZW50VmVyTnRmGGUg",
            "ASgLMhguZ2FtZV9wcm90by5DbGllbnRWZXJOdGYSLwoMZ21Db21tYW5kUmVx",
            "GMgBIAEoCzIYLmdhbWVfcHJvdG8uR01Db21tYW5kUmVxEi8KDGdtQ29tbWFu",
            "ZEFjaxjJASABKAsyGC5nYW1lX3Byb3RvLkdNQ29tbWFuZEFjaxInCghsb2dp",
            "blJlcRj0AyABKAsyFC5nYW1lX3Byb3RvLkxvZ2luUmVxEicKCGxvZ2luQWNr",
            "GPUDIAEoCzIULmdhbWVfcHJvdG8uTG9naW5BY2sSMQoNY3JlYXRlUm9sZVJl",
            "cRj+AyABKAsyGS5nYW1lX3Byb3RvLkNyZWF0ZVJvbGVSZXESMQoNY3JlYXRl",
            "Um9sZUFjaxj/AyABKAsyGS5nYW1lX3Byb3RvLkNyZWF0ZVJvbGVBY2sSMwoO",
            "c2V0Um9sZU5hbWVSZXEYiAQgASgLMhouZ2FtZV9wcm90by5TZXRSb2xlTmFt",
            "ZVJlcRIzCg5zZXRSb2xlTmFtZUFjaxiJBCABKAsyGi5nYW1lX3Byb3RvLlNl",
            "dFJvbGVOYW1lQWNrEi0KC3JvbGVJbmZvTnRmGJMEIAEoCzIXLmdhbWVfcHJv",
            "dG8uUm9sZUluZm9OdGYSLQoLbG9naW5FbmROdGYYnQQgASgLMhcuZ2FtZV9w",
            "cm90by5Mb2dpbkVuZE50ZhIvCgxzY2VuZUxvYWRSZXEY2AQgASgLMhguZ2Ft",
            "ZV9wcm90by5TY2VuZUxvYWRSZXESLwoMc2NlbmVMb2FkQWNrGNkEIAEoCzIY",
            "LmdhbWVfcHJvdG8uU2NlbmVMb2FkQWNrEi8KDHNjZW5lUm9sZVJlcRjiBCAB",
            "KAsyGC5nYW1lX3Byb3RvLlNjZW5lUm9sZVJlcRIvCgxzY2VuZVJvbGVBY2sY",
            "4wQgASgLMhguZ2FtZV9wcm90by5TY2VuZVJvbGVBY2sSLwoMc2NlbmVSb2xl",
            "TnRmGO0EIAEoCzIYLmdhbWVfcHJvdG8uU2NlbmVSb2xlTnRmEi0KC3NjZW5l",
            "TnBjTnRmGPcEIAEoCzIXLmdhbWVfcHJvdG8uU2NlbmVOcGNOdGYSLQoLbWFp",
            "bExpc3ROdGYYoQYgASgLMhcuZ2FtZV9wcm90by5NYWlsTGlzdE50ZhItCgtt",
            "YWlsT3BlblJlcRiqBiABKAsyFy5nYW1lX3Byb3RvLk1haWxPcGVuUmVxEi0K",
            "C21haWxPcGVuQWNrGKsGIAEoCzIXLmdhbWVfcHJvdG8uTWFpbE9wZW5BY2sS",
            "LQoLbWFpbEF0Y2hSZXEYtAYgASgLMhcuZ2FtZV9wcm90by5NYWlsQXRjaFJl",
            "cRItCgttYWlsQXRjaEFjaxi1BiABKAsyFy5nYW1lX3Byb3RvLk1haWxBdGNo",
            "QWNrEisKCm1haWxEZWxSZXEYvgYgASgLMhYuZ2FtZV9wcm90by5NYWlsRGVs",
            "UmVxEisKCm1haWxEZWxBY2sYvwYgASgLMhYuZ2FtZV9wcm90by5NYWlsRGVs",
            "QWNrKpUCCgNDbWQSCAoETk9ORRAAEggKBFBJTkcQARIRCg1DTElFTlRWRVJf",
            "TlRGEAoSDgoKR01fQ09NTUFORBAUEgkKBUxPR0lOEDISDwoLQ1JFQVRFX1JP",
            "TEUQMxIQCgxTRVRfUk9MRU5BTUUQNBIQCgxST0xFSU5GT19OVEYQNRIRCg1M",
            "T0dJTl9FTkRfTlRGEDYSDgoKU0NFTkVfTE9BRBA8Eg4KClNDRU5FX1JPTEUQ",
            "PRISCg5TQ0VORV9ST0xFX05URhA+EhEKDVNDRU5FX05QQ19OVEYQPxIRCg1N",
            "QUlMX0xJU1RfTlRGEFASDQoJTUFJTF9PUEVOEFESDQoJTUFJTF9BVENIEFIS",
            "DAoITUFJTF9ERUwQUyqSAQoJRXJyb3JDb2RlEgsKB1NVQ0NFU1MQABISCg5T",
            "RVJWSUNFX0NMT1NFRBABEhcKE1NFUlZJQ0VfVU5BVkFJTEFCTEUQAhIRCg1T",
            "RVJWSUNFX0RCTUFYEAMSEwoPVkVSU0lPTl9JTlZBTElEEAQSEQoNUEFSQU1f",
            "SU5WQUxJRBAFEhAKDE9QUkVBVEVfRkFTVBAGQgdaBXByb3RvUABiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameProto.GameReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CmdProto.Cmd), typeof(global::CmdProto.ErrorCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CmdProto.Ping), global::CmdProto.Ping.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CmdProto.CommonMessage), global::CmdProto.CommonMessage.Parser, new[]{ "Cmd", "ErrorCode", "Ping", "ClientVerNtf", "GmCommandReq", "GmCommandAck", "LoginReq", "LoginAck", "CreateRoleReq", "CreateRoleAck", "SetRoleNameReq", "SetRoleNameAck", "RoleInfoNtf", "LoginEndNtf", "SceneLoadReq", "SceneLoadAck", "SceneRoleReq", "SceneRoleAck", "SceneRoleNtf", "SceneNpcNtf", "MailListNtf", "MailOpenReq", "MailOpenAck", "MailAtchReq", "MailAtchAck", "MailDelReq", "MailDelAck" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Cmd {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("PING")] Ping = 1,
    /// <summary>
    ///Version
    /// </summary>
    [pbr::OriginalName("CLIENTVER_NTF")] ClientverNtf = 10,
    /// <summary>
    ///Cmd
    /// </summary>
    [pbr::OriginalName("GM_COMMAND")] GmCommand = 20,
    /// <summary>
    ///Login
    /// </summary>
    [pbr::OriginalName("LOGIN")] Login = 50,
    /// <summary>
    /// 创建角色
    /// </summary>
    [pbr::OriginalName("CREATE_ROLE")] CreateRole = 51,
    /// <summary>
    /// 设置角色名字
    /// </summary>
    [pbr::OriginalName("SET_ROLENAME")] SetRolename = 52,
    /// <summary>
    /// 角色信息
    /// </summary>
    [pbr::OriginalName("ROLEINFO_NTF")] RoleinfoNtf = 53,
    /// <summary>
    /// 登录结束
    /// </summary>
    [pbr::OriginalName("LOGIN_END_NTF")] LoginEndNtf = 54,
    /// <summary>
    ///Scene
    /// </summary>
    [pbr::OriginalName("SCENE_LOAD")] SceneLoad = 60,
    /// <summary>
    /// 场景玩家
    /// </summary>
    [pbr::OriginalName("SCENE_ROLE")] SceneRole = 61,
    /// <summary>
    /// 广播玩家数据
    /// </summary>
    [pbr::OriginalName("SCENE_ROLE_NTF")] SceneRoleNtf = 62,
    /// <summary>
    /// 广播NPC
    /// </summary>
    [pbr::OriginalName("SCENE_NPC_NTF")] SceneNpcNtf = 63,
    /// <summary>
    ///Mail
    /// </summary>
    [pbr::OriginalName("MAIL_LIST_NTF")] MailListNtf = 80,
    [pbr::OriginalName("MAIL_OPEN")] MailOpen = 81,
    [pbr::OriginalName("MAIL_ATCH")] MailAtch = 82,
    [pbr::OriginalName("MAIL_DEL")] MailDel = 83,
  }

  public enum ErrorCode {
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    /// 服务关闭
    /// </summary>
    [pbr::OriginalName("SERVICE_CLOSED")] ServiceClosed = 1,
    /// <summary>
    /// 服务繁忙
    /// </summary>
    [pbr::OriginalName("SERVICE_UNAVAILABLE")] ServiceUnavailable = 2,
    /// <summary>
    /// 禁止新用户进入
    /// </summary>
    [pbr::OriginalName("SERVICE_DBMAX")] ServiceDbmax = 3,
    /// <summary>
    /// 版本号不对
    /// </summary>
    [pbr::OriginalName("VERSION_INVALID")] VersionInvalid = 4,
    /// <summary>
    /// 参数不合法
    /// </summary>
    [pbr::OriginalName("PARAM_INVALID")] ParamInvalid = 5,
    /// <summary>
    /// 操作太快了
    /// </summary>
    [pbr::OriginalName("OPREATE_FAST")] OpreateFast = 6,
  }

  #endregion

  #region Messages
  public sealed partial class Ping : pb::IMessage<Ping>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Ping> _parser = new pb::MessageParser<Ping>(() => new Ping());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Ping> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CmdProto.CmdReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ping() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ping(Ping other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ping Clone() {
      return new Ping(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Ping);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Ping other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Ping other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  ///若字段没有被设置字段值，那么该字段在序列化时的数据中是完全不存在的，即不需要编码
  ///通用协议包装
  /// </summary>
  public sealed partial class CommonMessage : pb::IMessage<CommonMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CommonMessage> _parser = new pb::MessageParser<CommonMessage>(() => new CommonMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CommonMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CmdProto.CmdReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonMessage(CommonMessage other) : this() {
      cmd_ = other.cmd_;
      errorCode_ = other.errorCode_;
      ping_ = other.ping_ != null ? other.ping_.Clone() : null;
      clientVerNtf_ = other.clientVerNtf_ != null ? other.clientVerNtf_.Clone() : null;
      gmCommandReq_ = other.gmCommandReq_ != null ? other.gmCommandReq_.Clone() : null;
      gmCommandAck_ = other.gmCommandAck_ != null ? other.gmCommandAck_.Clone() : null;
      loginReq_ = other.loginReq_ != null ? other.loginReq_.Clone() : null;
      loginAck_ = other.loginAck_ != null ? other.loginAck_.Clone() : null;
      createRoleReq_ = other.createRoleReq_ != null ? other.createRoleReq_.Clone() : null;
      createRoleAck_ = other.createRoleAck_ != null ? other.createRoleAck_.Clone() : null;
      setRoleNameReq_ = other.setRoleNameReq_ != null ? other.setRoleNameReq_.Clone() : null;
      setRoleNameAck_ = other.setRoleNameAck_ != null ? other.setRoleNameAck_.Clone() : null;
      roleInfoNtf_ = other.roleInfoNtf_ != null ? other.roleInfoNtf_.Clone() : null;
      loginEndNtf_ = other.loginEndNtf_ != null ? other.loginEndNtf_.Clone() : null;
      sceneLoadReq_ = other.sceneLoadReq_ != null ? other.sceneLoadReq_.Clone() : null;
      sceneLoadAck_ = other.sceneLoadAck_ != null ? other.sceneLoadAck_.Clone() : null;
      sceneRoleReq_ = other.sceneRoleReq_ != null ? other.sceneRoleReq_.Clone() : null;
      sceneRoleAck_ = other.sceneRoleAck_ != null ? other.sceneRoleAck_.Clone() : null;
      sceneRoleNtf_ = other.sceneRoleNtf_ != null ? other.sceneRoleNtf_.Clone() : null;
      sceneNpcNtf_ = other.sceneNpcNtf_ != null ? other.sceneNpcNtf_.Clone() : null;
      mailListNtf_ = other.mailListNtf_ != null ? other.mailListNtf_.Clone() : null;
      mailOpenReq_ = other.mailOpenReq_ != null ? other.mailOpenReq_.Clone() : null;
      mailOpenAck_ = other.mailOpenAck_ != null ? other.mailOpenAck_.Clone() : null;
      mailAtchReq_ = other.mailAtchReq_ != null ? other.mailAtchReq_.Clone() : null;
      mailAtchAck_ = other.mailAtchAck_ != null ? other.mailAtchAck_.Clone() : null;
      mailDelReq_ = other.mailDelReq_ != null ? other.mailDelReq_.Clone() : null;
      mailDelAck_ = other.mailDelAck_ != null ? other.mailDelAck_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonMessage Clone() {
      return new CommonMessage(this);
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 1;
    private global::CmdProto.Cmd cmd_ = global::CmdProto.Cmd.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CmdProto.Cmd Cmd {
      get { return cmd_; }
      set {
        cmd_ = value;
      }
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 2;
    private global::CmdProto.ErrorCode errorCode_ = global::CmdProto.ErrorCode.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CmdProto.ErrorCode ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "ping" field.</summary>
    public const int PingFieldNumber = 3;
    private global::CmdProto.Ping ping_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CmdProto.Ping Ping {
      get { return ping_; }
      set {
        ping_ = value;
      }
    }

    /// <summary>Field number for the "clientVerNtf" field.</summary>
    public const int ClientVerNtfFieldNumber = 101;
    private global::GameProto.ClientVerNtf clientVerNtf_;
    /// <summary>
    ///通知客户端有新版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.ClientVerNtf ClientVerNtf {
      get { return clientVerNtf_; }
      set {
        clientVerNtf_ = value;
      }
    }

    /// <summary>Field number for the "gmCommandReq" field.</summary>
    public const int GmCommandReqFieldNumber = 200;
    private global::GameProto.GMCommandReq gmCommandReq_;
    /// <summary>
    ///GM命令
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.GMCommandReq GmCommandReq {
      get { return gmCommandReq_; }
      set {
        gmCommandReq_ = value;
      }
    }

    /// <summary>Field number for the "gmCommandAck" field.</summary>
    public const int GmCommandAckFieldNumber = 201;
    private global::GameProto.GMCommandAck gmCommandAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.GMCommandAck GmCommandAck {
      get { return gmCommandAck_; }
      set {
        gmCommandAck_ = value;
      }
    }

    /// <summary>Field number for the "loginReq" field.</summary>
    public const int LoginReqFieldNumber = 500;
    private global::GameProto.LoginReq loginReq_;
    /// <summary>
    /// Login
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.LoginReq LoginReq {
      get { return loginReq_; }
      set {
        loginReq_ = value;
      }
    }

    /// <summary>Field number for the "loginAck" field.</summary>
    public const int LoginAckFieldNumber = 501;
    private global::GameProto.LoginAck loginAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.LoginAck LoginAck {
      get { return loginAck_; }
      set {
        loginAck_ = value;
      }
    }

    /// <summary>Field number for the "createRoleReq" field.</summary>
    public const int CreateRoleReqFieldNumber = 510;
    private global::GameProto.CreateRoleReq createRoleReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CreateRoleReq CreateRoleReq {
      get { return createRoleReq_; }
      set {
        createRoleReq_ = value;
      }
    }

    /// <summary>Field number for the "createRoleAck" field.</summary>
    public const int CreateRoleAckFieldNumber = 511;
    private global::GameProto.CreateRoleAck createRoleAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CreateRoleAck CreateRoleAck {
      get { return createRoleAck_; }
      set {
        createRoleAck_ = value;
      }
    }

    /// <summary>Field number for the "setRoleNameReq" field.</summary>
    public const int SetRoleNameReqFieldNumber = 520;
    private global::GameProto.SetRoleNameReq setRoleNameReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SetRoleNameReq SetRoleNameReq {
      get { return setRoleNameReq_; }
      set {
        setRoleNameReq_ = value;
      }
    }

    /// <summary>Field number for the "setRoleNameAck" field.</summary>
    public const int SetRoleNameAckFieldNumber = 521;
    private global::GameProto.SetRoleNameAck setRoleNameAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SetRoleNameAck SetRoleNameAck {
      get { return setRoleNameAck_; }
      set {
        setRoleNameAck_ = value;
      }
    }

    /// <summary>Field number for the "roleInfoNtf" field.</summary>
    public const int RoleInfoNtfFieldNumber = 531;
    private global::GameProto.RoleInfoNtf roleInfoNtf_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.RoleInfoNtf RoleInfoNtf {
      get { return roleInfoNtf_; }
      set {
        roleInfoNtf_ = value;
      }
    }

    /// <summary>Field number for the "loginEndNtf" field.</summary>
    public const int LoginEndNtfFieldNumber = 541;
    private global::GameProto.LoginEndNtf loginEndNtf_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.LoginEndNtf LoginEndNtf {
      get { return loginEndNtf_; }
      set {
        loginEndNtf_ = value;
      }
    }

    /// <summary>Field number for the "sceneLoadReq" field.</summary>
    public const int SceneLoadReqFieldNumber = 600;
    private global::GameProto.SceneLoadReq sceneLoadReq_;
    /// <summary>
    /// Scene
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SceneLoadReq SceneLoadReq {
      get { return sceneLoadReq_; }
      set {
        sceneLoadReq_ = value;
      }
    }

    /// <summary>Field number for the "sceneLoadAck" field.</summary>
    public const int SceneLoadAckFieldNumber = 601;
    private global::GameProto.SceneLoadAck sceneLoadAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SceneLoadAck SceneLoadAck {
      get { return sceneLoadAck_; }
      set {
        sceneLoadAck_ = value;
      }
    }

    /// <summary>Field number for the "sceneRoleReq" field.</summary>
    public const int SceneRoleReqFieldNumber = 610;
    private global::GameProto.SceneRoleReq sceneRoleReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SceneRoleReq SceneRoleReq {
      get { return sceneRoleReq_; }
      set {
        sceneRoleReq_ = value;
      }
    }

    /// <summary>Field number for the "sceneRoleAck" field.</summary>
    public const int SceneRoleAckFieldNumber = 611;
    private global::GameProto.SceneRoleAck sceneRoleAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SceneRoleAck SceneRoleAck {
      get { return sceneRoleAck_; }
      set {
        sceneRoleAck_ = value;
      }
    }

    /// <summary>Field number for the "sceneRoleNtf" field.</summary>
    public const int SceneRoleNtfFieldNumber = 621;
    private global::GameProto.SceneRoleNtf sceneRoleNtf_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SceneRoleNtf SceneRoleNtf {
      get { return sceneRoleNtf_; }
      set {
        sceneRoleNtf_ = value;
      }
    }

    /// <summary>Field number for the "sceneNpcNtf" field.</summary>
    public const int SceneNpcNtfFieldNumber = 631;
    private global::GameProto.SceneNpcNtf sceneNpcNtf_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.SceneNpcNtf SceneNpcNtf {
      get { return sceneNpcNtf_; }
      set {
        sceneNpcNtf_ = value;
      }
    }

    /// <summary>Field number for the "mailListNtf" field.</summary>
    public const int MailListNtfFieldNumber = 801;
    private global::GameProto.MailListNtf mailListNtf_;
    /// <summary>
    ///Mail
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.MailListNtf MailListNtf {
      get { return mailListNtf_; }
      set {
        mailListNtf_ = value;
      }
    }

    /// <summary>Field number for the "mailOpenReq" field.</summary>
    public const int MailOpenReqFieldNumber = 810;
    private global::GameProto.MailOpenReq mailOpenReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.MailOpenReq MailOpenReq {
      get { return mailOpenReq_; }
      set {
        mailOpenReq_ = value;
      }
    }

    /// <summary>Field number for the "mailOpenAck" field.</summary>
    public const int MailOpenAckFieldNumber = 811;
    private global::GameProto.MailOpenAck mailOpenAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.MailOpenAck MailOpenAck {
      get { return mailOpenAck_; }
      set {
        mailOpenAck_ = value;
      }
    }

    /// <summary>Field number for the "mailAtchReq" field.</summary>
    public const int MailAtchReqFieldNumber = 820;
    private global::GameProto.MailAtchReq mailAtchReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.MailAtchReq MailAtchReq {
      get { return mailAtchReq_; }
      set {
        mailAtchReq_ = value;
      }
    }

    /// <summary>Field number for the "mailAtchAck" field.</summary>
    public const int MailAtchAckFieldNumber = 821;
    private global::GameProto.MailAtchAck mailAtchAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.MailAtchAck MailAtchAck {
      get { return mailAtchAck_; }
      set {
        mailAtchAck_ = value;
      }
    }

    /// <summary>Field number for the "mailDelReq" field.</summary>
    public const int MailDelReqFieldNumber = 830;
    private global::GameProto.MailDelReq mailDelReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.MailDelReq MailDelReq {
      get { return mailDelReq_; }
      set {
        mailDelReq_ = value;
      }
    }

    /// <summary>Field number for the "mailDelAck" field.</summary>
    public const int MailDelAckFieldNumber = 831;
    private global::GameProto.MailDelAck mailDelAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.MailDelAck MailDelAck {
      get { return mailDelAck_; }
      set {
        mailDelAck_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CommonMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CommonMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cmd != other.Cmd) return false;
      if (ErrorCode != other.ErrorCode) return false;
      if (!object.Equals(Ping, other.Ping)) return false;
      if (!object.Equals(ClientVerNtf, other.ClientVerNtf)) return false;
      if (!object.Equals(GmCommandReq, other.GmCommandReq)) return false;
      if (!object.Equals(GmCommandAck, other.GmCommandAck)) return false;
      if (!object.Equals(LoginReq, other.LoginReq)) return false;
      if (!object.Equals(LoginAck, other.LoginAck)) return false;
      if (!object.Equals(CreateRoleReq, other.CreateRoleReq)) return false;
      if (!object.Equals(CreateRoleAck, other.CreateRoleAck)) return false;
      if (!object.Equals(SetRoleNameReq, other.SetRoleNameReq)) return false;
      if (!object.Equals(SetRoleNameAck, other.SetRoleNameAck)) return false;
      if (!object.Equals(RoleInfoNtf, other.RoleInfoNtf)) return false;
      if (!object.Equals(LoginEndNtf, other.LoginEndNtf)) return false;
      if (!object.Equals(SceneLoadReq, other.SceneLoadReq)) return false;
      if (!object.Equals(SceneLoadAck, other.SceneLoadAck)) return false;
      if (!object.Equals(SceneRoleReq, other.SceneRoleReq)) return false;
      if (!object.Equals(SceneRoleAck, other.SceneRoleAck)) return false;
      if (!object.Equals(SceneRoleNtf, other.SceneRoleNtf)) return false;
      if (!object.Equals(SceneNpcNtf, other.SceneNpcNtf)) return false;
      if (!object.Equals(MailListNtf, other.MailListNtf)) return false;
      if (!object.Equals(MailOpenReq, other.MailOpenReq)) return false;
      if (!object.Equals(MailOpenAck, other.MailOpenAck)) return false;
      if (!object.Equals(MailAtchReq, other.MailAtchReq)) return false;
      if (!object.Equals(MailAtchAck, other.MailAtchAck)) return false;
      if (!object.Equals(MailDelReq, other.MailDelReq)) return false;
      if (!object.Equals(MailDelAck, other.MailDelAck)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Cmd != global::CmdProto.Cmd.None) hash ^= Cmd.GetHashCode();
      if (ErrorCode != global::CmdProto.ErrorCode.Success) hash ^= ErrorCode.GetHashCode();
      if (ping_ != null) hash ^= Ping.GetHashCode();
      if (clientVerNtf_ != null) hash ^= ClientVerNtf.GetHashCode();
      if (gmCommandReq_ != null) hash ^= GmCommandReq.GetHashCode();
      if (gmCommandAck_ != null) hash ^= GmCommandAck.GetHashCode();
      if (loginReq_ != null) hash ^= LoginReq.GetHashCode();
      if (loginAck_ != null) hash ^= LoginAck.GetHashCode();
      if (createRoleReq_ != null) hash ^= CreateRoleReq.GetHashCode();
      if (createRoleAck_ != null) hash ^= CreateRoleAck.GetHashCode();
      if (setRoleNameReq_ != null) hash ^= SetRoleNameReq.GetHashCode();
      if (setRoleNameAck_ != null) hash ^= SetRoleNameAck.GetHashCode();
      if (roleInfoNtf_ != null) hash ^= RoleInfoNtf.GetHashCode();
      if (loginEndNtf_ != null) hash ^= LoginEndNtf.GetHashCode();
      if (sceneLoadReq_ != null) hash ^= SceneLoadReq.GetHashCode();
      if (sceneLoadAck_ != null) hash ^= SceneLoadAck.GetHashCode();
      if (sceneRoleReq_ != null) hash ^= SceneRoleReq.GetHashCode();
      if (sceneRoleAck_ != null) hash ^= SceneRoleAck.GetHashCode();
      if (sceneRoleNtf_ != null) hash ^= SceneRoleNtf.GetHashCode();
      if (sceneNpcNtf_ != null) hash ^= SceneNpcNtf.GetHashCode();
      if (mailListNtf_ != null) hash ^= MailListNtf.GetHashCode();
      if (mailOpenReq_ != null) hash ^= MailOpenReq.GetHashCode();
      if (mailOpenAck_ != null) hash ^= MailOpenAck.GetHashCode();
      if (mailAtchReq_ != null) hash ^= MailAtchReq.GetHashCode();
      if (mailAtchAck_ != null) hash ^= MailAtchAck.GetHashCode();
      if (mailDelReq_ != null) hash ^= MailDelReq.GetHashCode();
      if (mailDelAck_ != null) hash ^= MailDelAck.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cmd != global::CmdProto.Cmd.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Cmd);
      }
      if (ErrorCode != global::CmdProto.ErrorCode.Success) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrorCode);
      }
      if (ping_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Ping);
      }
      if (clientVerNtf_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(ClientVerNtf);
      }
      if (gmCommandReq_ != null) {
        output.WriteRawTag(194, 12);
        output.WriteMessage(GmCommandReq);
      }
      if (gmCommandAck_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(GmCommandAck);
      }
      if (loginReq_ != null) {
        output.WriteRawTag(162, 31);
        output.WriteMessage(LoginReq);
      }
      if (loginAck_ != null) {
        output.WriteRawTag(170, 31);
        output.WriteMessage(LoginAck);
      }
      if (createRoleReq_ != null) {
        output.WriteRawTag(242, 31);
        output.WriteMessage(CreateRoleReq);
      }
      if (createRoleAck_ != null) {
        output.WriteRawTag(250, 31);
        output.WriteMessage(CreateRoleAck);
      }
      if (setRoleNameReq_ != null) {
        output.WriteRawTag(194, 32);
        output.WriteMessage(SetRoleNameReq);
      }
      if (setRoleNameAck_ != null) {
        output.WriteRawTag(202, 32);
        output.WriteMessage(SetRoleNameAck);
      }
      if (roleInfoNtf_ != null) {
        output.WriteRawTag(154, 33);
        output.WriteMessage(RoleInfoNtf);
      }
      if (loginEndNtf_ != null) {
        output.WriteRawTag(234, 33);
        output.WriteMessage(LoginEndNtf);
      }
      if (sceneLoadReq_ != null) {
        output.WriteRawTag(194, 37);
        output.WriteMessage(SceneLoadReq);
      }
      if (sceneLoadAck_ != null) {
        output.WriteRawTag(202, 37);
        output.WriteMessage(SceneLoadAck);
      }
      if (sceneRoleReq_ != null) {
        output.WriteRawTag(146, 38);
        output.WriteMessage(SceneRoleReq);
      }
      if (sceneRoleAck_ != null) {
        output.WriteRawTag(154, 38);
        output.WriteMessage(SceneRoleAck);
      }
      if (sceneRoleNtf_ != null) {
        output.WriteRawTag(234, 38);
        output.WriteMessage(SceneRoleNtf);
      }
      if (sceneNpcNtf_ != null) {
        output.WriteRawTag(186, 39);
        output.WriteMessage(SceneNpcNtf);
      }
      if (mailListNtf_ != null) {
        output.WriteRawTag(138, 50);
        output.WriteMessage(MailListNtf);
      }
      if (mailOpenReq_ != null) {
        output.WriteRawTag(210, 50);
        output.WriteMessage(MailOpenReq);
      }
      if (mailOpenAck_ != null) {
        output.WriteRawTag(218, 50);
        output.WriteMessage(MailOpenAck);
      }
      if (mailAtchReq_ != null) {
        output.WriteRawTag(162, 51);
        output.WriteMessage(MailAtchReq);
      }
      if (mailAtchAck_ != null) {
        output.WriteRawTag(170, 51);
        output.WriteMessage(MailAtchAck);
      }
      if (mailDelReq_ != null) {
        output.WriteRawTag(242, 51);
        output.WriteMessage(MailDelReq);
      }
      if (mailDelAck_ != null) {
        output.WriteRawTag(250, 51);
        output.WriteMessage(MailDelAck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cmd != global::CmdProto.Cmd.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Cmd);
      }
      if (ErrorCode != global::CmdProto.ErrorCode.Success) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrorCode);
      }
      if (ping_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Ping);
      }
      if (clientVerNtf_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(ClientVerNtf);
      }
      if (gmCommandReq_ != null) {
        output.WriteRawTag(194, 12);
        output.WriteMessage(GmCommandReq);
      }
      if (gmCommandAck_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(GmCommandAck);
      }
      if (loginReq_ != null) {
        output.WriteRawTag(162, 31);
        output.WriteMessage(LoginReq);
      }
      if (loginAck_ != null) {
        output.WriteRawTag(170, 31);
        output.WriteMessage(LoginAck);
      }
      if (createRoleReq_ != null) {
        output.WriteRawTag(242, 31);
        output.WriteMessage(CreateRoleReq);
      }
      if (createRoleAck_ != null) {
        output.WriteRawTag(250, 31);
        output.WriteMessage(CreateRoleAck);
      }
      if (setRoleNameReq_ != null) {
        output.WriteRawTag(194, 32);
        output.WriteMessage(SetRoleNameReq);
      }
      if (setRoleNameAck_ != null) {
        output.WriteRawTag(202, 32);
        output.WriteMessage(SetRoleNameAck);
      }
      if (roleInfoNtf_ != null) {
        output.WriteRawTag(154, 33);
        output.WriteMessage(RoleInfoNtf);
      }
      if (loginEndNtf_ != null) {
        output.WriteRawTag(234, 33);
        output.WriteMessage(LoginEndNtf);
      }
      if (sceneLoadReq_ != null) {
        output.WriteRawTag(194, 37);
        output.WriteMessage(SceneLoadReq);
      }
      if (sceneLoadAck_ != null) {
        output.WriteRawTag(202, 37);
        output.WriteMessage(SceneLoadAck);
      }
      if (sceneRoleReq_ != null) {
        output.WriteRawTag(146, 38);
        output.WriteMessage(SceneRoleReq);
      }
      if (sceneRoleAck_ != null) {
        output.WriteRawTag(154, 38);
        output.WriteMessage(SceneRoleAck);
      }
      if (sceneRoleNtf_ != null) {
        output.WriteRawTag(234, 38);
        output.WriteMessage(SceneRoleNtf);
      }
      if (sceneNpcNtf_ != null) {
        output.WriteRawTag(186, 39);
        output.WriteMessage(SceneNpcNtf);
      }
      if (mailListNtf_ != null) {
        output.WriteRawTag(138, 50);
        output.WriteMessage(MailListNtf);
      }
      if (mailOpenReq_ != null) {
        output.WriteRawTag(210, 50);
        output.WriteMessage(MailOpenReq);
      }
      if (mailOpenAck_ != null) {
        output.WriteRawTag(218, 50);
        output.WriteMessage(MailOpenAck);
      }
      if (mailAtchReq_ != null) {
        output.WriteRawTag(162, 51);
        output.WriteMessage(MailAtchReq);
      }
      if (mailAtchAck_ != null) {
        output.WriteRawTag(170, 51);
        output.WriteMessage(MailAtchAck);
      }
      if (mailDelReq_ != null) {
        output.WriteRawTag(242, 51);
        output.WriteMessage(MailDelReq);
      }
      if (mailDelAck_ != null) {
        output.WriteRawTag(250, 51);
        output.WriteMessage(MailDelAck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Cmd != global::CmdProto.Cmd.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Cmd);
      }
      if (ErrorCode != global::CmdProto.ErrorCode.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
      }
      if (ping_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ping);
      }
      if (clientVerNtf_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ClientVerNtf);
      }
      if (gmCommandReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(GmCommandReq);
      }
      if (gmCommandAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(GmCommandAck);
      }
      if (loginReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LoginReq);
      }
      if (loginAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LoginAck);
      }
      if (createRoleReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CreateRoleReq);
      }
      if (createRoleAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CreateRoleAck);
      }
      if (setRoleNameReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SetRoleNameReq);
      }
      if (setRoleNameAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SetRoleNameAck);
      }
      if (roleInfoNtf_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RoleInfoNtf);
      }
      if (loginEndNtf_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LoginEndNtf);
      }
      if (sceneLoadReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SceneLoadReq);
      }
      if (sceneLoadAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SceneLoadAck);
      }
      if (sceneRoleReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SceneRoleReq);
      }
      if (sceneRoleAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SceneRoleAck);
      }
      if (sceneRoleNtf_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SceneRoleNtf);
      }
      if (sceneNpcNtf_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SceneNpcNtf);
      }
      if (mailListNtf_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MailListNtf);
      }
      if (mailOpenReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MailOpenReq);
      }
      if (mailOpenAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MailOpenAck);
      }
      if (mailAtchReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MailAtchReq);
      }
      if (mailAtchAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MailAtchAck);
      }
      if (mailDelReq_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MailDelReq);
      }
      if (mailDelAck_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MailDelAck);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CommonMessage other) {
      if (other == null) {
        return;
      }
      if (other.Cmd != global::CmdProto.Cmd.None) {
        Cmd = other.Cmd;
      }
      if (other.ErrorCode != global::CmdProto.ErrorCode.Success) {
        ErrorCode = other.ErrorCode;
      }
      if (other.ping_ != null) {
        if (ping_ == null) {
          Ping = new global::CmdProto.Ping();
        }
        Ping.MergeFrom(other.Ping);
      }
      if (other.clientVerNtf_ != null) {
        if (clientVerNtf_ == null) {
          ClientVerNtf = new global::GameProto.ClientVerNtf();
        }
        ClientVerNtf.MergeFrom(other.ClientVerNtf);
      }
      if (other.gmCommandReq_ != null) {
        if (gmCommandReq_ == null) {
          GmCommandReq = new global::GameProto.GMCommandReq();
        }
        GmCommandReq.MergeFrom(other.GmCommandReq);
      }
      if (other.gmCommandAck_ != null) {
        if (gmCommandAck_ == null) {
          GmCommandAck = new global::GameProto.GMCommandAck();
        }
        GmCommandAck.MergeFrom(other.GmCommandAck);
      }
      if (other.loginReq_ != null) {
        if (loginReq_ == null) {
          LoginReq = new global::GameProto.LoginReq();
        }
        LoginReq.MergeFrom(other.LoginReq);
      }
      if (other.loginAck_ != null) {
        if (loginAck_ == null) {
          LoginAck = new global::GameProto.LoginAck();
        }
        LoginAck.MergeFrom(other.LoginAck);
      }
      if (other.createRoleReq_ != null) {
        if (createRoleReq_ == null) {
          CreateRoleReq = new global::GameProto.CreateRoleReq();
        }
        CreateRoleReq.MergeFrom(other.CreateRoleReq);
      }
      if (other.createRoleAck_ != null) {
        if (createRoleAck_ == null) {
          CreateRoleAck = new global::GameProto.CreateRoleAck();
        }
        CreateRoleAck.MergeFrom(other.CreateRoleAck);
      }
      if (other.setRoleNameReq_ != null) {
        if (setRoleNameReq_ == null) {
          SetRoleNameReq = new global::GameProto.SetRoleNameReq();
        }
        SetRoleNameReq.MergeFrom(other.SetRoleNameReq);
      }
      if (other.setRoleNameAck_ != null) {
        if (setRoleNameAck_ == null) {
          SetRoleNameAck = new global::GameProto.SetRoleNameAck();
        }
        SetRoleNameAck.MergeFrom(other.SetRoleNameAck);
      }
      if (other.roleInfoNtf_ != null) {
        if (roleInfoNtf_ == null) {
          RoleInfoNtf = new global::GameProto.RoleInfoNtf();
        }
        RoleInfoNtf.MergeFrom(other.RoleInfoNtf);
      }
      if (other.loginEndNtf_ != null) {
        if (loginEndNtf_ == null) {
          LoginEndNtf = new global::GameProto.LoginEndNtf();
        }
        LoginEndNtf.MergeFrom(other.LoginEndNtf);
      }
      if (other.sceneLoadReq_ != null) {
        if (sceneLoadReq_ == null) {
          SceneLoadReq = new global::GameProto.SceneLoadReq();
        }
        SceneLoadReq.MergeFrom(other.SceneLoadReq);
      }
      if (other.sceneLoadAck_ != null) {
        if (sceneLoadAck_ == null) {
          SceneLoadAck = new global::GameProto.SceneLoadAck();
        }
        SceneLoadAck.MergeFrom(other.SceneLoadAck);
      }
      if (other.sceneRoleReq_ != null) {
        if (sceneRoleReq_ == null) {
          SceneRoleReq = new global::GameProto.SceneRoleReq();
        }
        SceneRoleReq.MergeFrom(other.SceneRoleReq);
      }
      if (other.sceneRoleAck_ != null) {
        if (sceneRoleAck_ == null) {
          SceneRoleAck = new global::GameProto.SceneRoleAck();
        }
        SceneRoleAck.MergeFrom(other.SceneRoleAck);
      }
      if (other.sceneRoleNtf_ != null) {
        if (sceneRoleNtf_ == null) {
          SceneRoleNtf = new global::GameProto.SceneRoleNtf();
        }
        SceneRoleNtf.MergeFrom(other.SceneRoleNtf);
      }
      if (other.sceneNpcNtf_ != null) {
        if (sceneNpcNtf_ == null) {
          SceneNpcNtf = new global::GameProto.SceneNpcNtf();
        }
        SceneNpcNtf.MergeFrom(other.SceneNpcNtf);
      }
      if (other.mailListNtf_ != null) {
        if (mailListNtf_ == null) {
          MailListNtf = new global::GameProto.MailListNtf();
        }
        MailListNtf.MergeFrom(other.MailListNtf);
      }
      if (other.mailOpenReq_ != null) {
        if (mailOpenReq_ == null) {
          MailOpenReq = new global::GameProto.MailOpenReq();
        }
        MailOpenReq.MergeFrom(other.MailOpenReq);
      }
      if (other.mailOpenAck_ != null) {
        if (mailOpenAck_ == null) {
          MailOpenAck = new global::GameProto.MailOpenAck();
        }
        MailOpenAck.MergeFrom(other.MailOpenAck);
      }
      if (other.mailAtchReq_ != null) {
        if (mailAtchReq_ == null) {
          MailAtchReq = new global::GameProto.MailAtchReq();
        }
        MailAtchReq.MergeFrom(other.MailAtchReq);
      }
      if (other.mailAtchAck_ != null) {
        if (mailAtchAck_ == null) {
          MailAtchAck = new global::GameProto.MailAtchAck();
        }
        MailAtchAck.MergeFrom(other.MailAtchAck);
      }
      if (other.mailDelReq_ != null) {
        if (mailDelReq_ == null) {
          MailDelReq = new global::GameProto.MailDelReq();
        }
        MailDelReq.MergeFrom(other.MailDelReq);
      }
      if (other.mailDelAck_ != null) {
        if (mailDelAck_ == null) {
          MailDelAck = new global::GameProto.MailDelAck();
        }
        MailDelAck.MergeFrom(other.MailDelAck);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Cmd = (global::CmdProto.Cmd) input.ReadEnum();
            break;
          }
          case 16: {
            ErrorCode = (global::CmdProto.ErrorCode) input.ReadEnum();
            break;
          }
          case 26: {
            if (ping_ == null) {
              Ping = new global::CmdProto.Ping();
            }
            input.ReadMessage(Ping);
            break;
          }
          case 810: {
            if (clientVerNtf_ == null) {
              ClientVerNtf = new global::GameProto.ClientVerNtf();
            }
            input.ReadMessage(ClientVerNtf);
            break;
          }
          case 1602: {
            if (gmCommandReq_ == null) {
              GmCommandReq = new global::GameProto.GMCommandReq();
            }
            input.ReadMessage(GmCommandReq);
            break;
          }
          case 1610: {
            if (gmCommandAck_ == null) {
              GmCommandAck = new global::GameProto.GMCommandAck();
            }
            input.ReadMessage(GmCommandAck);
            break;
          }
          case 4002: {
            if (loginReq_ == null) {
              LoginReq = new global::GameProto.LoginReq();
            }
            input.ReadMessage(LoginReq);
            break;
          }
          case 4010: {
            if (loginAck_ == null) {
              LoginAck = new global::GameProto.LoginAck();
            }
            input.ReadMessage(LoginAck);
            break;
          }
          case 4082: {
            if (createRoleReq_ == null) {
              CreateRoleReq = new global::GameProto.CreateRoleReq();
            }
            input.ReadMessage(CreateRoleReq);
            break;
          }
          case 4090: {
            if (createRoleAck_ == null) {
              CreateRoleAck = new global::GameProto.CreateRoleAck();
            }
            input.ReadMessage(CreateRoleAck);
            break;
          }
          case 4162: {
            if (setRoleNameReq_ == null) {
              SetRoleNameReq = new global::GameProto.SetRoleNameReq();
            }
            input.ReadMessage(SetRoleNameReq);
            break;
          }
          case 4170: {
            if (setRoleNameAck_ == null) {
              SetRoleNameAck = new global::GameProto.SetRoleNameAck();
            }
            input.ReadMessage(SetRoleNameAck);
            break;
          }
          case 4250: {
            if (roleInfoNtf_ == null) {
              RoleInfoNtf = new global::GameProto.RoleInfoNtf();
            }
            input.ReadMessage(RoleInfoNtf);
            break;
          }
          case 4330: {
            if (loginEndNtf_ == null) {
              LoginEndNtf = new global::GameProto.LoginEndNtf();
            }
            input.ReadMessage(LoginEndNtf);
            break;
          }
          case 4802: {
            if (sceneLoadReq_ == null) {
              SceneLoadReq = new global::GameProto.SceneLoadReq();
            }
            input.ReadMessage(SceneLoadReq);
            break;
          }
          case 4810: {
            if (sceneLoadAck_ == null) {
              SceneLoadAck = new global::GameProto.SceneLoadAck();
            }
            input.ReadMessage(SceneLoadAck);
            break;
          }
          case 4882: {
            if (sceneRoleReq_ == null) {
              SceneRoleReq = new global::GameProto.SceneRoleReq();
            }
            input.ReadMessage(SceneRoleReq);
            break;
          }
          case 4890: {
            if (sceneRoleAck_ == null) {
              SceneRoleAck = new global::GameProto.SceneRoleAck();
            }
            input.ReadMessage(SceneRoleAck);
            break;
          }
          case 4970: {
            if (sceneRoleNtf_ == null) {
              SceneRoleNtf = new global::GameProto.SceneRoleNtf();
            }
            input.ReadMessage(SceneRoleNtf);
            break;
          }
          case 5050: {
            if (sceneNpcNtf_ == null) {
              SceneNpcNtf = new global::GameProto.SceneNpcNtf();
            }
            input.ReadMessage(SceneNpcNtf);
            break;
          }
          case 6410: {
            if (mailListNtf_ == null) {
              MailListNtf = new global::GameProto.MailListNtf();
            }
            input.ReadMessage(MailListNtf);
            break;
          }
          case 6482: {
            if (mailOpenReq_ == null) {
              MailOpenReq = new global::GameProto.MailOpenReq();
            }
            input.ReadMessage(MailOpenReq);
            break;
          }
          case 6490: {
            if (mailOpenAck_ == null) {
              MailOpenAck = new global::GameProto.MailOpenAck();
            }
            input.ReadMessage(MailOpenAck);
            break;
          }
          case 6562: {
            if (mailAtchReq_ == null) {
              MailAtchReq = new global::GameProto.MailAtchReq();
            }
            input.ReadMessage(MailAtchReq);
            break;
          }
          case 6570: {
            if (mailAtchAck_ == null) {
              MailAtchAck = new global::GameProto.MailAtchAck();
            }
            input.ReadMessage(MailAtchAck);
            break;
          }
          case 6642: {
            if (mailDelReq_ == null) {
              MailDelReq = new global::GameProto.MailDelReq();
            }
            input.ReadMessage(MailDelReq);
            break;
          }
          case 6650: {
            if (mailDelAck_ == null) {
              MailDelAck = new global::GameProto.MailDelAck();
            }
            input.ReadMessage(MailDelAck);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Cmd = (global::CmdProto.Cmd) input.ReadEnum();
            break;
          }
          case 16: {
            ErrorCode = (global::CmdProto.ErrorCode) input.ReadEnum();
            break;
          }
          case 26: {
            if (ping_ == null) {
              Ping = new global::CmdProto.Ping();
            }
            input.ReadMessage(Ping);
            break;
          }
          case 810: {
            if (clientVerNtf_ == null) {
              ClientVerNtf = new global::GameProto.ClientVerNtf();
            }
            input.ReadMessage(ClientVerNtf);
            break;
          }
          case 1602: {
            if (gmCommandReq_ == null) {
              GmCommandReq = new global::GameProto.GMCommandReq();
            }
            input.ReadMessage(GmCommandReq);
            break;
          }
          case 1610: {
            if (gmCommandAck_ == null) {
              GmCommandAck = new global::GameProto.GMCommandAck();
            }
            input.ReadMessage(GmCommandAck);
            break;
          }
          case 4002: {
            if (loginReq_ == null) {
              LoginReq = new global::GameProto.LoginReq();
            }
            input.ReadMessage(LoginReq);
            break;
          }
          case 4010: {
            if (loginAck_ == null) {
              LoginAck = new global::GameProto.LoginAck();
            }
            input.ReadMessage(LoginAck);
            break;
          }
          case 4082: {
            if (createRoleReq_ == null) {
              CreateRoleReq = new global::GameProto.CreateRoleReq();
            }
            input.ReadMessage(CreateRoleReq);
            break;
          }
          case 4090: {
            if (createRoleAck_ == null) {
              CreateRoleAck = new global::GameProto.CreateRoleAck();
            }
            input.ReadMessage(CreateRoleAck);
            break;
          }
          case 4162: {
            if (setRoleNameReq_ == null) {
              SetRoleNameReq = new global::GameProto.SetRoleNameReq();
            }
            input.ReadMessage(SetRoleNameReq);
            break;
          }
          case 4170: {
            if (setRoleNameAck_ == null) {
              SetRoleNameAck = new global::GameProto.SetRoleNameAck();
            }
            input.ReadMessage(SetRoleNameAck);
            break;
          }
          case 4250: {
            if (roleInfoNtf_ == null) {
              RoleInfoNtf = new global::GameProto.RoleInfoNtf();
            }
            input.ReadMessage(RoleInfoNtf);
            break;
          }
          case 4330: {
            if (loginEndNtf_ == null) {
              LoginEndNtf = new global::GameProto.LoginEndNtf();
            }
            input.ReadMessage(LoginEndNtf);
            break;
          }
          case 4802: {
            if (sceneLoadReq_ == null) {
              SceneLoadReq = new global::GameProto.SceneLoadReq();
            }
            input.ReadMessage(SceneLoadReq);
            break;
          }
          case 4810: {
            if (sceneLoadAck_ == null) {
              SceneLoadAck = new global::GameProto.SceneLoadAck();
            }
            input.ReadMessage(SceneLoadAck);
            break;
          }
          case 4882: {
            if (sceneRoleReq_ == null) {
              SceneRoleReq = new global::GameProto.SceneRoleReq();
            }
            input.ReadMessage(SceneRoleReq);
            break;
          }
          case 4890: {
            if (sceneRoleAck_ == null) {
              SceneRoleAck = new global::GameProto.SceneRoleAck();
            }
            input.ReadMessage(SceneRoleAck);
            break;
          }
          case 4970: {
            if (sceneRoleNtf_ == null) {
              SceneRoleNtf = new global::GameProto.SceneRoleNtf();
            }
            input.ReadMessage(SceneRoleNtf);
            break;
          }
          case 5050: {
            if (sceneNpcNtf_ == null) {
              SceneNpcNtf = new global::GameProto.SceneNpcNtf();
            }
            input.ReadMessage(SceneNpcNtf);
            break;
          }
          case 6410: {
            if (mailListNtf_ == null) {
              MailListNtf = new global::GameProto.MailListNtf();
            }
            input.ReadMessage(MailListNtf);
            break;
          }
          case 6482: {
            if (mailOpenReq_ == null) {
              MailOpenReq = new global::GameProto.MailOpenReq();
            }
            input.ReadMessage(MailOpenReq);
            break;
          }
          case 6490: {
            if (mailOpenAck_ == null) {
              MailOpenAck = new global::GameProto.MailOpenAck();
            }
            input.ReadMessage(MailOpenAck);
            break;
          }
          case 6562: {
            if (mailAtchReq_ == null) {
              MailAtchReq = new global::GameProto.MailAtchReq();
            }
            input.ReadMessage(MailAtchReq);
            break;
          }
          case 6570: {
            if (mailAtchAck_ == null) {
              MailAtchAck = new global::GameProto.MailAtchAck();
            }
            input.ReadMessage(MailAtchAck);
            break;
          }
          case 6642: {
            if (mailDelReq_ == null) {
              MailDelReq = new global::GameProto.MailDelReq();
            }
            input.ReadMessage(MailDelReq);
            break;
          }
          case 6650: {
            if (mailDelAck_ == null) {
              MailDelAck = new global::GameProto.MailDelAck();
            }
            input.ReadMessage(MailDelAck);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
