// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSGameStartInfoHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSGameStartInfo packetImpl = (CSGameStartInfo)packet;
            Log.Info("Receive packet '{0}'.", packetImpl.GetType().ToString());

            // Tcp Session。
            Session session = (Session)sender;
            // User。
            Server.User user = (Server.User)session.BindInfo;

            if (user == null || user.Room == null)
            {
                Log.Error($"CSGameStartInfoHandler Error");
                return;
            }

            SCGameStartInfo gameStartInfo = ReferencePool.Acquire<SCGameStartInfo>();
            gameStartInfo.RoomId = user.Room.RoomId;
            gameStartInfo.MapId = 1;
            gameStartInfo.LocalId = user.LocalId;
            gameStartInfo.UserCount = user.Room.GetCurrCount();
            gameStartInfo.Seed = 0;
            // 遍历添加所有人信息，添加到 SCGameStartInfo
            foreach (KeyValuePair<long, Server.User> kvp in user.Room.GetUsersDictionary())
            {
                UserGameInfo userGameInfo = new UserGameInfo();
                userGameInfo.LocalId = kvp.Value.LocalId;
                userGameInfo.UserState = (int)kvp.Value.UserState;
                userGameInfo.User = new User();
                userGameInfo.User.UserId = kvp.Value.UserId;
                userGameInfo.User.UserName = kvp.Value.UserName;

                gameStartInfo.UserGameInfos.Add(userGameInfo);
            }
            user.TcpSession?.Send(gameStartInfo);
        }
    }
}
