// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSGameStartInfoHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSGameStartInfo packetImpl = (CSGameStartInfo)packet;
            Log.Info("Receive packet '{0}'.", packetImpl.GetType().ToString());

            // Tcp Session。
            Session session = (Session)sender;
            // User。
            Server.User user = (Server.User)session.BindInfo;

            if (user == null || user.Room == null)
            {
                Log.Error($"CSGameStartInfoHandler Error");
                return;
            }

            SCGameStartInfo gameStartInfo = ReferencePool.Acquire<SCGameStartInfo>();
            gameStartInfo.RoomId = user.Room.RoomId;
            gameStartInfo.MapId = 1;
            gameStartInfo.LocalId = user.LocalId;
            gameStartInfo.UserCount = user.Room.GetCurrCount();
            gameStartInfo.Seed = 0;
            // 遍历添加所有人信息，添加到 SCGameStartInfo
            foreach (KeyValuePair<long, Server.User> kvp2 in user.Room.GetUsersDictionary())
            {
                GameProto.User tUser = new GameProto.User();
                tUser.UserId = kvp2.Value.UserId;
                tUser.UserName = kvp2.Value.UserName;
                gameStartInfo.Users.Add(tUser);
            }
            user.TcpSession?.Send(gameStartInfo);
        }
    }
}
