// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSGameControlCodeHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSGameControlCode packetImpl = (CSGameControlCode)packet;
            Log.Info("Receive packet '{0}'.", packetImpl.GetType().ToString());

            //Tcp Session¡£
            Session session = (Session)sender;
            //User¡£
            Server.User user = (Server.User)session.BindInfo;

            EGameControlCode gameControlCode = (EGameControlCode)packetImpl.GameControlCode;
  
            switch (gameControlCode)
            {
                case EGameControlCode.Pause:
                    Log.Info("CSGameControlCodeHandler - Pause.");

                    break;
                case EGameControlCode.Resume:
                    Log.Info("CSGameControlCodeHandler - Resume.");

                    break;
                case EGameControlCode.Quit:
                    Log.Info("CSGameControlCodeHandler - Quit.");
                    user?.Room?.QuitGame(user);
                    break;
                default:
                    break;
            }
        }
    }
}
