// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSHashCodeHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSHashCode packetImpl = (CSHashCode)packet;
            //Log.Info("Receive packet '{0}'.", packetImpl.GetType().ToString());

            //Tcp Session¡£
            Session session = (Session)sender;
            //User¡£
            Server.User user = (Server.User)session.BindInfo;

            user?.Room?.Game.OnCheckHashCode(user, packetImpl);
        }
    }
}
