// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework.Runtime;
using Network;

namespace GameProto
{
    public partial class CSHashCodeHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSHashCode packetImpl = (CSHashCode)packet;
            Log.Info("Receive packet '{0}'.", packetImpl.Id.ToString());
        }
    }
}
