// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSJoinRoomHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSJoinRoom packetImpl = (CSJoinRoom)packet;
            Log.Info("Receive Packet Type:'{0}', Id:{1}", packetImpl.GetType().ToString(), packetImpl.Id.ToString());

            // Tcp Session。
            Session session = (Session)sender;
            // Server.User。
            Server.User user = (Server.User)session.BindInfo;

            // Create Room.
            Room availableRoom = GameEntry.GameLogic.RoomManager.GetAvailableRoom();
            if (availableRoom == null)
            {
                availableRoom = ReferencePool.Acquire<Room>();
                availableRoom.RoomId = RoomIdGenerator.GenerateId();
                availableRoom.RoomName = user.Account;
                availableRoom.JoinRoom(user);
                GameEntry.GameLogic.RoomManager.AddRoom(availableRoom);
            }
            else
            {
                availableRoom.JoinRoom(user);
            }

            // 广播客户端有人加入房间。
            foreach (KeyValuePair<long, Server.User> kvp in availableRoom.GetUsersDictionary())
            {
                Server.User sUser = kvp.Value;
                SCJoinRoom scJoinRoom = ReferencePool.Acquire<SCJoinRoom>();
                scJoinRoom.RoomId = availableRoom.RoomId;
                scJoinRoom.LocalId = user.LocalId;
                // 遍历添加所有人信息，添加到 SCJoinRoom
                foreach (KeyValuePair<long, Server.User> kvp2 in availableRoom.GetUsersDictionary())
                {
                    UserReadyInfo userReadyInfo = new UserReadyInfo();
                    userReadyInfo.LocalId = kvp2.Value.LocalId;
                    userReadyInfo.Status = kvp2.Value.IsReady ? 1 : 0;
                    userReadyInfo.User = new User();
                    userReadyInfo.User.UserId = kvp2.Value.UserId;
                    userReadyInfo.User.UserName = kvp2.Value.UserName;
                    scJoinRoom.UserReadyInfos.Add(userReadyInfo);
                }
                sUser.TcpSession.Send(scJoinRoom);
            }
        }
    }
}
