// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSLoginHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSLogin packetImpl = (CSLogin)packet;
            Log.Info("Receive Packet Type:'{0}', Id:{1}", packetImpl.GetType().ToString(), packetImpl.Id.ToString());

            // tcp Session。
            Session session = (Session)sender;

            // Create user。
            User user = ReferencePool.Acquire<User>();
            user.UserId = UserIdGenerator.GenerateId();
            user.Account = packetImpl.Account;
            user.Password = packetImpl.Password;
            user.TcpSession = session;
            GameEntry.Game.AddUser(user);

            // 回客户端消息。
            SCLogin scLogin = ReferencePool.Acquire<SCLogin>();
            // TODO:暂定 1 为登录成功。
            scLogin.State = 1;
            session.Send(scLogin);
        }
    }
}
