// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSLoginHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSLogin packetImpl = (CSLogin)packet;
            //Log.Info("Receive Packet Type:'{0}'", packetImpl.GetType().ToString());

            // Tcp Session。
            Session session = (Session)sender;
            bool isPasswordCorrect = true;

            // TODO:Get From DB，这里应该从数据中获取User信息。
            // Get User。
            Server.User user = GameEntry.GameLogic.UserManager.GetUser(packetImpl.Account);

            if (user == null)
            {
                // 离线后的登录。
                // Create user。
                user = ReferencePool.Acquire<Server.User>();
                user.UserId = UserIdGenerator.GenerateId();     //Get From DB.
                user.Account = packetImpl.Account;
                user.Password = packetImpl.Password;
                user.UserName = packetImpl.Account;
                user.TcpSession = session;
                user.UserState = EUserState.LoggedIn;

                session.BindInfo = user;

                GameEntry.GameLogic.UserManager.AddUser(user);
            }
            else
            {
                // 重新登录或者短线重连。
                Log.Error("CSLoginHandler Reconnected...");

                // Reset Session。
                user.TcpSession = session;

                session.BindInfo = user;

                if (packetImpl.Password != user.Password)
                {
                    isPasswordCorrect = false;
                }
            }

            // 回客户端消息。
            SCLogin scLogin = ReferencePool.Acquire<SCLogin>();
            if(isPasswordCorrect)
            {
                scLogin.RetCode = (int)EErrorCode.Success;
            }
            else
            {
                scLogin.RetCode = (int)EErrorCode.IncorrectPassword;
            }
            scLogin.UserState = (int)user.UserState;
            
            session.Send(scLogin);
        }
    }
}
