// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Lockstep.Util;
using Network;
using Server;

namespace GameProto
{
    public partial class CSPingHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSPing packetImpl = (CSPing)packet;
            //Log.Info("Receive packet '{0}'.", packetImpl.GetType().ToString());

            // Tcp Session¡£
            Session session = (Session)sender;
            // Server.User¡£
            Server.User user = (Server.User)session.BindInfo;

            SCPing ping = ReferencePool.Acquire<SCPing>();
            ping.LocalId = user.LocalId;
            ping.SendTimestamp = packetImpl.SendTimestamp;
            ping.TimeSinceServerStart = GameTime.CurrTimeStamp - user.Room.Game.GameStartTimestampMs;
            user.TcpSession?.Send(ping);
        }
    }
}
