// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework;
using BaseFramework.Runtime;
using Network;
using Server;

namespace GameProto
{
    public partial class CSReadyHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            CSReady packetImpl = (CSReady)packet;
            Log.Info("Receive Packet Type:'{0}', Id:{1}", packetImpl.GetType().ToString(), packetImpl.Id.ToString());

            // Tcp Session。
            Session session = (Session)sender;
            // User。
            Server.User user = (Server.User)session.BindInfo;
            // 设置为准备状态。
            user.IsReady = packetImpl.Status == 1;

            Room room = user.Room;
            if(room == null)
            {
                Log.Error("CSReadyHandler Error : Room is null.");
                return;
            }

            if (room.IsAllReady())
            {
                // 全部准备，广播客户端开始游戏的消息。
                foreach (KeyValuePair<long, Server.User> kvp in room.GetUsersDictionary())
                {
                    Server.User sUser = kvp.Value;
                    SCGameStartInfo gameStartInfo = ReferencePool.Acquire<SCGameStartInfo>();
                    gameStartInfo.RoomId = room.RoomId;
                    gameStartInfo.MapId = 1;
                    gameStartInfo.LocalId = sUser.LocalId;
                    gameStartInfo.UserCount = room.GetCurrCount();
                    gameStartInfo.Seed = 0;
                    // 遍历添加所有人信息，添加到 SCGameStartInfo
                    foreach (KeyValuePair<long, Server.User> kvp2 in room.GetUsersDictionary())
                    {
                        GameProto.User tUser = new GameProto.User();
                        tUser.UserId = kvp2.Value.UserId;
                        tUser.UserName = kvp2.Value.UserName;
                        gameStartInfo.Users.Add(tUser);
                    }
                    sUser.TcpSession.Send(gameStartInfo);
                }

                room.Game.SetLoading();
            }
            else
            {
                // 非全部准备，广播客户端有人准备。
                foreach (KeyValuePair<long, Server.User> kvp in room.GetUsersDictionary())
                {
                    Server.User sUser = kvp.Value;
                    SCReady scReady = ReferencePool.Acquire<SCReady>();
                    // 遍历添加所有人信息，添加到 SCReady
                    foreach (KeyValuePair<long, Server.User> kvp2 in room.GetUsersDictionary())
                    {
                        UserReadyInfo userReadyInfo = new UserReadyInfo();
                        userReadyInfo.LocalId = kvp2.Value.LocalId;
                        userReadyInfo.Status = kvp2.Value.IsReady ? 1 : 0;
                        userReadyInfo.User = new User();
                        userReadyInfo.User.UserId = kvp2.Value.UserId;
                        userReadyInfo.User.UserName = kvp2.Value.UserName;
                        scReady.UserReadyInfos.Add(userReadyInfo);
                    }
                    sUser.TcpSession.Send(scReady);
                }
            }
        }
    }
}
