// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework.Network;
using UnityBaseFramework.Runtime;
using XGame;

namespace GameProto
{
    public partial class SCGameControlCodeHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            SCGameControlCode packetImpl = (SCGameControlCode)packet;
            Log.Info("Receive packet '{0}'.", packetImpl.GetType().ToString());

            GameEntry.Event.Fire(sender, SCGameControlCodeEventArgs.Create(packetImpl.GameControlCode));
        }
    }
}
