// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework.Network;
using UnityBaseFramework.Runtime;
using XGame;

namespace GameProto
{
    public partial class SCReqMissFrameHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            SCReqMissFrame packetImpl = (SCReqMissFrame)packet;
            //Log.Info("Receive Packet Type:'{0}'", packetImpl.GetType().ToString());

            GameEntry.Event.Fire(sender, SCReqMissFrameEventArgs.Create(packetImpl.StartTick, packetImpl.ServerFrames));
        }
    }
}
