// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handle' function yourself.
// </auto-generated>

using BaseFramework.Network;
using UnityBaseFramework.Runtime;
using XGame;

namespace GameProto
{
    public partial class SCServerFrameHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            SCServerFrame packetImpl = (SCServerFrame)packet;
            Log.Info("Receive Packet Type:'{0}', Id:{1}", packetImpl.GetType().ToString(), packetImpl.Id.ToString());

            //Log.Error("SCServerFrame.Tick {0}", packetImpl.ServerFrames[packetImpl.ServerFrames.Count - 1].Tick);
            GameEntry.Event.Fire(sender, SCServerFrameEventArgs.Create(packetImpl.StartTick, packetImpl.ServerFrames));
        }
    }
}
