// <auto-generated>
//   This file will only be generated once
//   and will not be overwritten.
//   You need to implement the 'Handler' function yourself.
// </auto-generated>

using BaseFramework.Runtime;

namespace Network
{
    public partial class SCLoginVerifyHandler : PacketHandlerBase
    {
        public override void Handle(object sender, Packet packet)
        {
            SCLoginVerify packetImpl = (SCLoginVerify)packet;
            Log.Info("Receive packet '{0}'.", packetImpl.Id.ToString());
        }
    }
}
